all:
	ocamlc -g lang.ml levenshtein.ml soundex.ml robert.ml robertdev.ml main.ml
mli:
	ocamlc -i lang.ml levenshtein.ml soundex.ml robert.ml robertdev.ml main.ml
dev:
	ocamlc -g lang.ml levenshtein.ml soundex.ml robert.ml robertdev.ml
clean::
	rm -f *.cm[iox] *- .*~ *.o *.out
